### ISSUE TITLE
Save As ability

### ISSUE THREAD

**Issue by kylemfspurgeon** [LArSoft/webevd#35]
Implement ability to save current screen/canvas to image file. Possible extension to animated gif?

**Comment by kylemfspurgeon** [comment]
https://stackoverflow.com/questions/15558418/how-do-you-save-an-image-from-a-three-js-canvas

https://stackoverflow.com/questions/923885/capture-html-canvas-as-gif-jpg-png-pdf

Possible resources.

**Comment by cjbacchus** [comment]
Initial implementation in https://github.com/LArSoft/webevd/tree/feature/save_image
